# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the externalDB directory into the container at /app
COPY . /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Run mainApp.py when the container launches
CMD ["python", "/app/mainApp.py"]
